#!/bin/bash
# usage: bash setup <machine_name>

if [ "$1" ]; then
	# bash profile
	if [ ! -f $(pwd)/.bash_profile_$1 ]; then
		touch $(pwd)/.bash_profile_$1
	fi
	CMD="ln -s $(pwd)/.bash_profile_$1 ~/.bash_profile"
	echo "${CMD}"
	eval "${CMD}"

	# bash common
	CMD="ln -s $(pwd)/.bash_common ~/.bash_common"
	echo "${CMD}"
	eval "${CMD}"

	# vim
	CMD="ln -s $(pwd) ~/.vim"
	echo "${CMD}"
	eval "${CMD}"
	CMD="ln -s $(pwd)/.vimrc ~/.vimrc"
	echo "${CMD}"
	eval "${CMD}"
	CMD="vim +PluginInstall +qall"
	echo "${CMD}"
	eval "${CMD}"

	# tmux
	CMD="ln -s $(pwd)/.tmux.conf ~/.tmux.conf"
	echo "${CMD}"
	eval "${CMD}"

	# ack
	CMD="ln -s $(pwd)/.ackrc ~/.ackrc"
	echo "${CMD}"
	eval "${CMD}"

	# create .bash_aliases
	CMD="touch ~/.bash_aliases"
	echo "${CMD}"
	eval "${CMD}"

	# copy git config if one doesn't exist yet
	if [ ! -f ~/.gitconfig ]; then
		CMD="cp $(pwd)/gitconfig ~/.gitconfig"
		echo "${CMD}"
		eval "${CMD}"
	fi

	# create vim swap directories if they don't exist
	if [ ! -d $(pwd)/.vim_backup ]; then
		CMD="mkdir $(pwd)/.vim_backup"
		echo "${CMD}"
		eval "${CMD}"
	fi
	if [ ! -d $(pwd)/.vim_swap ]; then
		CMD="mkdir $(pwd)/.vim_swap"
		echo "${CMD}"
		eval "${CMD}"
	fi

else
	echo "You must pass the name of the machine so I can setup the bash profile.  This will create a file called .bash_profile_[INPUT]"
fi
