#!/bin/bash

# git-recent
# Author: AppNexus DevOps Team <devops@appnexus.com>

if [[ $* == *-h* ]] || [[ $* == *--help* ]]
then
  echo "Call 'git fetch' and log all remote branches that have any activity"
	echo
  echo "usage: git recent [<options>]"
	echo "<num> number of days to lookback (default 1)"
  echo "<-s/--short> print only branch names"
	echo
  exit 0
fi

if [[ $1 =~ ^[0-9]+$ ]]
then
  days=$1
elif [[ $2 =~ ^[0-9]+$ ]]
then
	days=$2
else
	days=1
fi

FORMAT='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'
LOG_PARAMS=("--pretty=format:$FORMAT" "--abbrev-commit" "--date=relative" "--since=$days.days")

git fetch
PRINT_BREAK=0
for b in $(git branch -r | grep -v HEAD | awk '{print $1}'); do
  output=$(git log "${LOG_PARAMS[@]}" $b)
  if [[ -n $output ]]
  then
		if [[ $* == *-s* ]] || [[ $* == *--short* ]]
		then
			echo $b
		else
			if [[ $PRINT_BREAK -eq 1 ]]
			then
				echo
			else
				PRINT_BREAK=1
			fi
			echo "Branch: $b"
			echo "$output"
		fi
  fi
done
