#!/bin/bash

# git-stats
# Print ownership statistics for the file list provided in stdin
#
# Author: AppNexus DevOps Team <devops@appnexus.com>


if [[ $* == *-h* ]] || [[ $* == *--help* ]]
then
  echo "Print the line ownership statistics for the file list provided in stdin"
  echo "The owner is considered to be whoever last modified the line"
  echo
  echo "usage: git ls-files | git stats"
  echo
  exit 0
fi

input=`cat`
echo "$input"  | xargs -I {} git blame {} | perl -n -e '/^.*\((.*?)\s*[\d]{4}-[\d]{2}/; print $1,"\n"' | sort -f | uniq -c | sort -n
