#!/bin/bash

# git-rlog
# Print a short commit log for each branch in the remote
#
# Author: AppNexus DevOps Team <devops@appnexus.com>


if [[ $* == *-h* ]] || [[ $* == *--help* ]]
then
  echo "Print a short commit log for each branch in the remote ('remote log' => 'rlog')"
  echo
  echo "usage: git rlog [<options>]"
  echo "<num> Limit log to num commits"
  echo
  exit 0
fi

if [[ -z "$1" ]]
then
  num_commits=5
else
  num_commits=$1
fi

FORMAT='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an, %ae>%Creset'
LOG_PARAMS=("--pretty=format:$FORMAT" "--abbrev-commit" "--date=relative" "-n $num_commits")

git fetch
PRINT_BREAK=0
for b in $(git branch -r | grep -v HEAD | awk '{print $1}'); do
  output=$(git log "${LOG_PARAMS[@]}" $b)
  if [[ $PRINT_BREAK -eq 1 ]]
  then
    echo
  else
    PRINT_BREAK=1
  fi
  echo "Branch: $b"
  echo "$output"
done
